name: BLACKGOLDLINK
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b0b0b2'
    - '#8a8a8a'
    - '#2b2b2b'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
