name: BLACKGOLDLINK
favicon: null
layout_spectrum: 0.6853880775161088
typography_spectrum: 0.42284974036738276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#444444'
    - '#636363'
    - '#bdbdbd'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
